auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Chong Zhou
url: http://rf-mems.github.io/
feed: /atom.xml
author_info: <a href="http://rf-mems.github.io/">Chong Zhou</a>
